### ISSUE TITLE
softlock on nightmare castle -  smell of the past or condemned area

### ISSUE THREAD

**Issue by granfalloon** [Aceearly1993/lecarde-1#15]
if you continue falling and miss the exit here 
![image](https://github.com/Aceearly1993/lecarde-1/assets/15142608/6e25df3c-42ee-4017-8c17-e57796bae327)
you continue falling and will get stuck before you're able to fall further or die, making you have to restart the entire level

**Comment by Aceearly1993** [comment]
This is a quirk about animation orders after converted the game project to new editions of the engine. Fixed in the next version.
