### ISSUE TITLE
Platform bug softlock (Gardens)

### ISSUE THREAD

**Issue by lunatixxx** [Aceearly1993/lecarde-1#19]
After i opened the locked passage from the left i come to this area for the first time in this run, killed the medusa and destroyed the candle with axe. After that i could not go back by pressing down and jump like if there were an invisible floor, i was forced to alt f4 ultimately. Not sure if it is a combination of things that triggered it.

https://clips.twitch.tv/DiligentFaithfulGorillaRitzMitz-_MKGsDMfoNSLEQRd

**Comment by Aceearly1993** [comment]
I failed to reproduce this bug but now I added one more regulation to rule out potential obj overlap which may responsible for this behavior.

**Comment by Aceearly1993** [comment]
what do you mean? You mean the original issue is still intact in 0.5.3?

**Comment by Aceearly1993** [comment]
A couple more in-depth details would help. Anyway I adjusted the position of platform and updated the commit at 0.5.3 (it's technically 0.5.3c now) please check if the platform still bugs or not.
