### ISSUE TITLE
Bug with new setting menu on map 

### ISSUE THREAD

**Issue by lunatixxx** [Aceearly1993/lecarde-1#20]
When i used the added settings menu from the map in last version, i lost my sub weapon in the next level.

https://www.twitch.tv/videos/2158318860

**Comment by Aceearly1993** [comment]
The function to remember current sub weapon will be supported in the next commit to 0.5.3 branch.

**Comment by Aceearly1993** [comment]
Please check the new commit which just dropped at 0.5.3 branch.
