### ISSUE TITLE
Mirror boss softlock

### ISSUE THREAD

**Issue by lunatixxx** [Aceearly1993/lecarde-1#22]
The boss took a lot of time to come back to the mirror but then the fight continued, except that when i broke the last mirror he did go to the left outside of the arena and never came back.
https://www.twitch.tv/videos/2161588073

**Comment by Aceearly1993** [comment]
I cannot take any changes to it on my own without additional collaborator (s).

**Comment by Aceearly1993** [comment]
In reworked edition, the air wall bug that pushes efrain out of bound in boss rush had been fixed.

**Comment by Aceearly1993** [comment]
Did you check the latest commit at 0.5.5 and it's still possible to make the boss permanently disappear?
