### ISSUE TITLE
Horseman boss animation freeze

### ISSUE THREAD

**Issue by lunatixxx** [Aceearly1993/lecarde-1#25]
This seems to be a quite rare bug as it is the first time it happens for me, it seems to be caused by the subweapon threw at the right moment ?

https://youtu.be/e5NVf2BWYho

**Comment by Aceearly1993** [comment]
It's a core system of the boss behavior I won't touch anything related to it as long as it's not serious softlocking.

**Comment by Aceearly1993** [comment]
I'll have to repeat It's too dangerous for me to take it alone unlike the "new" bugs generated by controller plugin update/swap, which I can revert to original state if I screwed up anything critical.
