### ISSUE TITLE
 Music bug on first boss (always since 0.5.5)

### ISSUE THREAD

**Issue by lunatixxx** [Aceearly1993/lecarde-1#26]
I did 4 runs with version 0.5.5 and the music of the first level never stop when you reach the boss, it continues even in the cinematic and stop until you are on the bridge. Only happen for the first boss it was not happening with 0.5.4. or before.

https://youtu.be/VMrDLUmau2g

**Comment by Aceearly1993** [comment]
I don't know why it happen I didn't touch pointers related to this. Anyway it will been fixed in the next commit of 0.5.5.
