### ISSUE TITLE
Inconsistent sub weapon candle

### ISSUE THREAD

**Issue by lunatixxx** [Aceearly1993/lecarde-1#32]
I noticed that in the first fight against the death the candle that drop the axe will ocasionnally only give a big heart, same thing for the cross in the preparation room of the final boss. Not sure what causes that i suppose that it is a bug.

**Comment by Aceearly1993** [comment]
It's a design intention instead of a bug. Depending on if you've destroyed 2 or more candles in a single strike the drops may be different from striking the candles regularly one by one.
