### ISSUE TITLE
Controller bug with xinput gamepad

### ISSUE THREAD

**Issue by lunatixxx** [Aceearly1993/lecarde-1#34]
Between screen transition if i continue to press a direction (right for example) the character now stop and i have to release the button and press it again, it was never happening in 0.5.6 version. 

_This is different from the last thing that i reported "Two spots where the slide skill can break", this one was already in previous versions._

I used the native fullscreen DX11 (0.5.8) on windows 10

**Comment by Aceearly1993** [comment]
very unfortunately that's how fusion's system works with the point of view directions I cannot do more. I don't know how will the situation be in SDL joystick plugins but it will certainly take a behemoth size amount of time, which I did not bother and it's best leave this to someone else who has time.
