### ISSUE TITLE
Problem with F7/Ctrl+F2 - Build 0.5.8

### ISSUE THREAD

**Issue by Felipefpl** [Aceearly1993/lecarde-1#36]
I tested F7 to see what happens but nothing happens.

When pressing Ctrl+F2 to reset the game the size of windows goes back to minimized instead of the maximized state that it was before. It's annoying having to maximize the window everytime we reset the game. :/

**Comment by Aceearly1993** [comment]
It's not impossible to make such list on my end but I'm less motivated for something as subtle and niche as that. So the readme will most likely remain in its current shape.
