### ISSUE TITLE
Cosmetic suggestions - Build 0.58

### ISSUE THREAD

**Issue by Felipefpl** [Aceearly1993/lecarde-1#37]
The font in the words "New Game" and below doesnt look good for some reason. I'm using the DX 11 version.
![Untitled](https://github.com/user-attachments/assets/0d23fec9-347e-4aa7-bede-6921271a9be9)

Also, it's missing a capital letter on "normal", unlike it happens with easy/hard settings.

The number of the build should be in the main screen.

**Comment by Aceearly1993** [comment]
The vanilla font is incompatible with DX11 and this is the best what I can do to make the came compatible with DX11. Sorry.
