### ISSUE TITLE
Problem with the saves - Build 0.5.8

### ISSUE THREAD

**Issue by Felipefpl** [Aceearly1993/lecarde-1#38]
I noticed there are 2 kinds of data the game doesnt save:

1 - The number of hearts you had before (when you load a game their number is always zero even after i filled them to the maximum).

2 - The location where you set your character (you always are in the main town even after you saved in another location).

Was that intended by the devs or those are just minor problems?

**Comment by Aceearly1993** [comment]
I don't have plans to change what was already established in vanilla.
