### ISSUE TITLE
Feature Request - Sound Control

### ISSUE THREAD

**Issue by Felipefpl** [Aceearly1993/lecarde-1#39]
I had to reduce my realtek's sound from 80 to 50 because the audio volume is loud and we cant reduce it in-game. Is it possible to add volume sliders for SFX/Music/Voices?

**Comment by Aceearly1993** [comment]
I cannot add such function because the vanilla sound data structure is bad and all over the place. Add another GUI will increase the risk of breaking more structures in ways I cannot see.
