### ISSUE TITLE
2 Problems - Build 0.5.8

### ISSUE THREAD

**Issue by Felipefpl** [Aceearly1993/lecarde-1#42]
I saw while fixing the language file that the monk has some dialog with Efrain where he says he's not feeling well. I didnt get this dialog while playing the game.

A HUGE WARNING should be on first page WITH CAPITAL LETTERS telling ppl that we MUST play the game on hard difficulty to see the true ending. This is something i found when reading the language file too. I'm glad i deleted the game because i didnt want to have this surprise in case i played the game to the end.

**Comment by Aceearly1993** [comment]
the part of priest not feeling well is not actually used in game.

the text format is laid there for any future localization purposes and nothing more. Anything difficulty setting-wise is out of my concern.

**Comment by Aceearly1993** [comment]
Bugs seem serious or dangerous (crash exits, graphic disorder or softlocks) will be valid target to be report.

**Comment by Aceearly1993** [comment]
Some of the texts are stored as pictures unfortunately editing pictures is really giving me headache and it will be a behemoth amount of troubles making edited pictures display in the game correctly.

**Comment by Aceearly1993** [comment]
I fear I can't I did not have the necessary stylized font at start screen to indicate a new language. And I won't consider another language unless if the request is too many like simplified Chinese. A region flag indicator might be possible but I fear the 640x480 resolution cannot hold as much region flag indicators as 8.
