### ISSUE TITLE
Problem with the text being/not being displayed

### ISSUE THREAD

**Issue by Felipefpl** [Aceearly1993/lecarde-1#43]
There is a problem below right after the 1st boss is defeated:

"P1:
You got the power: ITEM CRASH LEVEL 1

P2:
Now you can use your subweapon in a more powerful way.

P3:
The red numbers indicate how many hearts are needed to use the current item crash.

P4:
Press UP and item crash button to use it.

P5:
(With enough hearts)"

The phrase "With enough hearts" is displayed with the green color like if it was a ability used with SP.

Now this one:

"P5:
The Von Viltheim main castle lies on a lake in northern Austria.

P6:
Two brothers Wilhelm and Leopold and the sister Katharina live there.

P7:
I should go to Austria and investigate..."

The P6 phrase isnt displayed here after i defeated the 1st boss. I played on hard mode in case that matters.

Btw, i noticed you made an update. That's somewhat bad since i made a few small improvements to the english file again because of a few things i missed when fixing the errors. An oversight of my side. :P

**Comment by Aceearly1993** [comment]
the text color is not something very important or emergency.

the P6 is not actually utilized in game.
